In [3]:
import numpy as np

## Numpy
The numpy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays. 
### 1. Creating arrays

In [28]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[1.5, 2, 3], [4, 5, 6]])   # the same as b

In [29]:
b.shape, b.shape[0], len(b), b.ndim, b.size

((2, 3), 2, 2, 2, 6)

In [30]:
b.dtype, b.dtype.name, b.astype(int)

(dtype('float64'), 'float64', array([[1, 2, 3],
        [4, 5, 6]]))

### 2. Initial Placeholders

In [31]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((2, 3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [36]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [37]:
np.random.random((2, 2))

array([[0.47862549, 0.55821764],
       [0.19003483, 0.26343519]])

In [38]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [39]:
np.arange(10, 25, 5)

array([10, 15, 20])

## 3 Array manipulation

In [41]:
x = np.array([[1, 2], [3, 4]])

In [42]:
x.flatten()

array([1, 2, 3, 4])

In [43]:
x.ravel()

array([1, 2, 3, 4])

In [44]:
x.flatten('F')

array([1, 3, 2, 4])

In [45]:
x.ravel('F')

array([1, 3, 2, 4])

In [46]:
x.flatten()[1] = 100
x

array([[1, 2],
       [3, 4]])

In [47]:
x.ravel()[1] = 100
x

array([[  1, 100],
       [  3,   4]])

In [52]:
y = np.array([[1, 1], [2, 2]])
np.concatenate((x, y), axis=0)

array([[  1, 100],
       [  3,   4],
       [  1,   1],
       [  2,   2]])